import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AuthProvider from "./components/AuthProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <AuthProvider>
          <header className="border-b">
          <nav className="mx-auto max-w-6xl px-4 py-3 flex items-center gap-4">
            <a href="/" className="font-semibold">Crafted Portfolio</a>
            <div className="text-sm flex gap-3">
              <a href="/personas/saas" className="hover:underline">SaaS Admin Console</a>
              <a href="/personas/ai" className="hover:underline">AI Content Ops Hub</a>
              <a href="/personas/ecommerce" className="hover:underline">E‑Commerce Engine</a>
              <a href="/personas/healthcare" className="hover:underline">Patient Portal</a>
              <a href="/personas/logistics" className="hover:underline">Logistics Command Center</a>
            </div>
          </nav>
        </header>
        <main className="mx-auto max-w-6xl px-4 py-6">
          {children}
        </main>
        <footer className="border-t mt-8">
          <div className="mx-auto max-w-6xl px-4 py-4 text-sm text-gray-500">
            Demo apps showcasing enterprise capabilities.
          </div>
        </footer>
          </AuthProvider>
      </body>
    </html>
  );
}
